### ISSUE TITLE
Resolved

### ISSUE THREAD

**Issue by ghost** [KyleLopin/Potentiostat_GUI#3]
Resolved

**Comment by shuvragood** [comment]
I am having all code with me (https://drive.google.com/drive/folders/1hKyy2O2HLyh9o4wxKsPFoyXOMyaorkv7)

https://www.duo.uio.no/bitstream/handle/10852/82665/5/Olav-Bjerke---masteroppgave.pdf .

Getting USB Time out error while replicating this into CY8CKIT-059
